name: Building kernel

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      COMPILER:
        description: 'compilers used'
        required: true
        default: 'Geopelia-Clang'
      KREPO:
        description: 'kernel repo'
        required: true
        default: 'https://github.com/erabye/android_kernel_xiaomi_selene'
      KBRANCH:
        description: 'kernel branch'
        required: true
        default: 'pragmatism'
      ZREPO:
        description: 'zipper repo'
        required: false
        default: ''
      ZBRANCH:
        description: 'zipper branch'
        required: false
        default: ''
      KSU:
        description: 'if dont want ksu then leave blank'
        required: false
        default: 'both'
      CONTAINER:
        description: 'if you know you know'
        required: true
        default: 'fedora:40'

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  REPO: ${{ github.event.inputs.KREPO }}
  RUN_NUM: ${{ github.run_number }}_${{ github.run_attempt }}
  KERNEL_BRANCH: ${{ github.event.inputs.KBRANCH }}
  COMPILERS: ${{ github.event.inputs.COMPILER }}
  PATCH_KSU: ${{ github.event.inputs.KSU }}
  zipper_repo: ${{ github.event.inputs.ZREPO }}
  zipper_branch: ${{ github.event.inputs.ZBRANCH }}
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.CONTAINER }}

    steps:
        - name: checkout
          uses: actions/checkout@master
        - name: init build env
          run: |
            dnf group install development-tools -y
            dnf install llvm lld bc bison ca-certificates curl flex glibc-devel.i686 glibc-devel binutils-devel openssl python3 python2 zstd clang gcc-arm-linux-gnu dtc libxml2 libarchive openssl-devel perl tomsfastmath-devel wget xz -y
            ln -sf "/usr/bin/python3" /usr/bin/python
            git config --global user.name "John Doe"
            git config --global user.email "idk@example.com"
        - name: clone kernel source
          run: git clone --depth=1 --single-branch $REPO -b $KERNEL_BRANCH kernel
        - name: print kernel info
          run: |
            cd kernel
            source ../env
            echo "gh $RUN_NUM: kernel name: ${kernel_name}%nlgh $RUN_NUM: kernel ver: ${kernel_ver}%nlgh $RUN_NUM: kernel head commit: ${kernel_head}%nlgh $RUN_NUM: defconfig: ${defconfig}"
        - name: run compilation scripts
          run: |
            cd kernel
            case $PATCH_KSU in
              "both" )
                echo "gh $RUN_NUM: running compilation script(s): $COMPILERS"
                bash ../build.sh "$COMPILERS"
                echo "gh $RUN_NUM: KernelSU patching enabled, patching"
                bash ../ksu/applyPatches.sh
                echo "gh $RUN_NUM: running compilation script(s): $COMPILERS"
                bash ../build.sh "$COMPILERS"
              ;;
              "" )
                echo "gh $RUN_NUM: running compilation script(s): $COMPILERS"
                bash ../build.sh "$COMPILERS"
              ;;
              * )
                echo "gh $RUN_NUM: KernelSU patching enabled, patching"
                bash ../ksu/applyPatches.sh
                echo "gh $RUN_NUM: running compilation script(s): $COMPILERS"
                bash ../build.sh "$COMPILERS"
              ;;
            esac
        - uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ env.RUN_NUM }}
            files: |
              kernel/*.zip
              kernel/*.log
